
apiVersion: v1
kind: Service
metadata:
  name: "appvm02"
  namespace: "demo-erdem"
  annotations:
    metallb.universe.tf/address-pool: example
spec:
  ports:
  - port: 22
    name: "ssh"
    targetPort: 22
  - port: 80
    name: "http"
    targetPort: 80
  selector:
    kubevirt.io/domain: "appvm02"
  type: LoadBalancer