apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: frontend_appvm01-virt-demo-rhel8
  namespace: demo-erdem
spec:
  dataVolumeTemplates:
    - metadata:
        name: frontend_appvm01-virt-demo-rhel8-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel8
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  instancetype:
    name: u1.large
  preference:
    name: rhel.8
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: frontend_appvm01-virt-demo-rhel8-disk
            - disk:
                bus: virtio
              name: cloudinitdisk
      volumes:
        - dataVolume:
            name: frontend_appvm01-virt-demo-rhel8-volume
          name: frontend_appvm01-virt-demo-rhel8-disk
        - cloudInitConfigDrive:
            userData: |
              #cloud-config
              user: quasys
              password: virtdemo
              chpasswd:
                expire: false
          name: cloudinitdisk
